# Generated by Django 3.1.3 on 2020-12-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweb',
            name='instructorName',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='dweb',
            name='provider',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
